version: '3'
services:
  webapp:
    image: node:8
    working_dir: /app
    volumes:
      - ".:/app"  
    command: /app/start-node.sh
    ports:
      - 4100
    links:
      - postgres
  postgres:
    image: postgres:10
    ports:
      - 5432
    volumes:
      - "./sql/init.sql:/docker-entrypoint-initdb.d/init.sql"