#!/bin/bash

docker-compose up -d
docker-compose exec webapp cat /app/demo/genesisPassphrase.bitcoin.json
ip=$(ifconfig eth0 | grep 'inet addr' | cut -d: -f2 | awk '{print $1}')
port=$(docker-compose ps webapp | grep '/app/start-node' | cut -d: -f2 | cut -d- -f1)
echo ""
echo "http://$ip:$port"